pipeline {
    agent any
    stages {
        stage ('Run img docker') {   
            steps {
                sh 'docker run -d --rm -p 8080:8080 --name redis redis'
            }
        }
    }
}
